/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param expiresInMillis 
 * @param remainingCalls 
 * @param resetsInMillis 
 * @param token 
 * @param totalRequests 
 * @param valid 
 */
data class ApiTokenStatus (
    val expiresInMillis: kotlin.Long? = null,
    val remainingCalls: kotlin.Long? = null,
    val resetsInMillis: kotlin.Long? = null,
    val token: kotlin.String? = null,
    val totalRequests: kotlin.Long? = null,
    val valid: kotlin.Boolean? = null
) {

}

