/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param expiresInMillis
 * @param remainingCalls
 * @param resetsInMillis
 * @param token
 * @param totalRequests
 * @param valid
 */
data class ApiTokenStatus(
        val expiresInMillis: Long? = null,
        val remainingCalls: Long? = null,
        val resetsInMillis: Long? = null,
        val token: String? = null,
        val totalRequests: Long? = null,
        val valid: Boolean? = null
)

