/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param attributionText
 * @param attributionUrl
 * @param audioType
 * @param commentCount
 * @param createdAt
 * @param createdBy
 * @param description
 * @param duration
 * @param fileUrl
 * @param id
 * @param voteAverage
 * @param voteCount
 * @param voteWeightedAverage
 * @param word
 */
data class AudioFile(
        val id: Long,
        val attributionText: String? = null,
        val attributionUrl: String? = null,
        val audioType: String? = null,
        val commentCount: Int? = null,
        val createdAt: java.time.LocalDateTime? = null,
        val createdBy: String? = null,
        val description: String? = null,
        val duration: Double? = null,
        val fileUrl: String? = null,
        val voteAverage: Float? = null,
        val voteCount: Int? = null,
        val voteWeightedAverage: Float? = null,
        val word: String? = null
)

