/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param attributionText 
 * @param attributionUrl 
 * @param audioType 
 * @param commentCount 
 * @param createdAt 
 * @param createdBy 
 * @param description 
 * @param duration 
 * @param fileUrl 
 * @param id 
 * @param voteAverage 
 * @param voteCount 
 * @param voteWeightedAverage 
 * @param word 
 */
data class AudioFile (
    val id: kotlin.Long,
    val attributionText: kotlin.String? = null,
    val attributionUrl: kotlin.String? = null,
    val audioType: kotlin.String? = null,
    val commentCount: kotlin.Int? = null,
    val createdAt: java.time.LocalDateTime? = null,
    val createdBy: kotlin.String? = null,
    val description: kotlin.String? = null,
    val duration: kotlin.Double? = null,
    val fileUrl: kotlin.String? = null,
    val voteAverage: kotlin.Float? = null,
    val voteCount: kotlin.Int? = null,
    val voteWeightedAverage: kotlin.Float? = null,
    val word: kotlin.String? = null
) {

}

