/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param token 
 * @param userId 
 * @param userSignature 
 */
data class AuthenticationToken (
    val token: kotlin.String? = null,
    val userId: kotlin.Long? = null,
    val userSignature: kotlin.String? = null
) {

}

