/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param count
 * @param gram1
 * @param gram2
 * @param mi
 * @param wlmi
 */
data class Bigram(
        val count: Long? = null,
        val gram1: String? = null,
        val gram2: String? = null,
        val mi: Double? = null,
        val wlmi: Double? = null
)

