/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param attributionText 
 * @param attributionUrl 
 * @param citations 
 * @param exampleUses 
 * @param extendedText 
 * @param labels 
 * @param notes 
 * @param partOfSpeech 
 * @param relatedWords 
 * @param score 
 * @param seqString 
 * @param sequence 
 * @param sourceDictionary 
 * @param text 
 * @param textProns 
 * @param word 
 */
data class Definition (
    val attributionText: kotlin.String? = null,
    val attributionUrl: kotlin.String? = null,
    val citations: kotlin.Array<kotlin.String>? = null,
    val exampleUses: kotlin.Array<kotlin.String>? = null,
    val extendedText: kotlin.String? = null,
    val labels: kotlin.Array<kotlin.String>? = null,
    val notes: kotlin.Array<kotlin.String>? = null,
    val partOfSpeech: kotlin.String? = null,
    val relatedWords: kotlin.Array<kotlin.String>? = null,
    val score: kotlin.Float? = null,
    val seqString: kotlin.String? = null,
    val sequence: kotlin.String? = null,
    val sourceDictionary: kotlin.String? = null,
    val text: kotlin.String? = null,
    val textProns: kotlin.Array<kotlin.String>? = null,
    val word: kotlin.String? = null
) {

}

