/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param attributionText
 * @param attributionUrl
 * @param citations
 * @param exampleUses
 * @param extendedText
 * @param labels
 * @param notes
 * @param partOfSpeech
 * @param relatedWords
 * @param score
 * @param seqString
 * @param sequence
 * @param sourceDictionary
 * @param text
 * @param textProns
 * @param word
 */
data class Definition(
        val attributionText: String? = null,
        val attributionUrl: String? = null,
        val citations: Array<String>? = null,
        val exampleUses: Array<String>? = null,
        val extendedText: String? = null,
        val labels: Array<String>? = null,
        val notes: Array<String>? = null,
        val partOfSpeech: String? = null,
        val relatedWords: Array<String>? = null,
        val score: Float? = null,
        val seqString: String? = null,
        val sequence: String? = null,
        val sourceDictionary: String? = null,
        val text: String? = null,
        val textProns: Array<String>? = null,
        val word: String? = null
)

