/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.ContentProvider
import io.swagger.client.models.ScoredWord
import io.swagger.client.models.Sentence

/**
 * 
 * @param documentId 
 * @param exampleId 
 * @param id 
 * @param provider 
 * @param rating 
 * @param score 
 * @param sentence 
 * @param text 
 * @param title 
 * @param url 
 * @param word 
 * @param year 
 */
data class Example (
    val documentId: kotlin.Long? = null,
    val exampleId: kotlin.Long? = null,
    val id: kotlin.Long? = null,
    val provider: ContentProvider? = null,
    val rating: kotlin.Float? = null,
    val score: ScoredWord? = null,
    val sentence: Sentence? = null,
    val text: kotlin.String? = null,
    val title: kotlin.String? = null,
    val url: kotlin.String? = null,
    val word: kotlin.String? = null,
    val year: kotlin.Int? = null
) {

}

