/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param frequency 
 * @param frequencyString 
 * @param totalCount 
 * @param unknownYearCount 
 * @param word 
 */
data class FrequencySummary (
    val frequency: kotlin.Array<kotlin.String>? = null,
    val frequencyString: kotlin.String? = null,
    val totalCount: kotlin.Long? = null,
    val unknownYearCount: kotlin.Int? = null,
    val word: kotlin.String? = null
) {

}

