/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param appliesTo 
 * @param noteType 
 * @param pos 
 * @param value 
 */
data class Note (
    val appliesTo: kotlin.Array<kotlin.String>? = null,
    val noteType: kotlin.String? = null,
    val pos: kotlin.Int? = null,
    val value: kotlin.String? = null
) {

}

