/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param gram 
 * @param label1 
 * @param label2 
 * @param label3 
 * @param label4 
 * @param relationshipType 
 * @param words 
 */
data class Related (
    val gram: kotlin.String? = null,
    val label1: kotlin.String? = null,
    val label2: kotlin.String? = null,
    val label3: kotlin.String? = null,
    val label4: kotlin.String? = null,
    val relationshipType: kotlin.String? = null,
    val words: kotlin.Array<kotlin.String>? = null
) {

}

