/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param categories 
 * @param id 
 * @param name 
 */
data class Root (
    val id: kotlin.Long,
    val categories: kotlin.Array<kotlin.String>? = null,
    val name: kotlin.String? = null
) {

}

