/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param baseWordScore 
 * @param docTermCount 
 * @param id 
 * @param lemma 
 * @param partOfSpeech 
 * @param position 
 * @param score 
 * @param sentenceId 
 * @param stopword 
 * @param word 
 * @param wordType 
 */
data class ScoredWord (
    val baseWordScore: kotlin.Double? = null,
    val docTermCount: kotlin.Int? = null,
    val id: kotlin.Long? = null,
    val lemma: kotlin.String? = null,
    val partOfSpeech: kotlin.String? = null,
    val position: kotlin.Int? = null,
    val score: kotlin.Float? = null,
    val sentenceId: kotlin.Long? = null,
    val stopword: kotlin.Boolean? = null,
    val word: kotlin.String? = null,
    val wordType: kotlin.String? = null
) {

}

