/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param baseWordScore
 * @param docTermCount
 * @param id
 * @param lemma
 * @param partOfSpeech
 * @param position
 * @param score
 * @param sentenceId
 * @param stopword
 * @param word
 * @param wordType
 */
data class ScoredWord(
        val baseWordScore: Double? = null,
        val docTermCount: Int? = null,
        val id: Long? = null,
        val lemma: String? = null,
        val partOfSpeech: String? = null,
        val position: Int? = null,
        val score: Float? = null,
        val sentenceId: Long? = null,
        val stopword: Boolean? = null,
        val word: String? = null,
        val wordType: String? = null
)

