/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param display 
 * @param documentMetadataId 
 * @param hasScoredWords 
 * @param id 
 * @param rating 
 * @param scoredWords 
 */
data class Sentence (
    val display: kotlin.String? = null,
    val documentMetadataId: kotlin.Long? = null,
    val hasScoredWords: kotlin.Boolean? = null,
    val id: kotlin.Long? = null,
    val rating: kotlin.Int? = null,
    val scoredWords: kotlin.Array<kotlin.String>? = null
) {

}

