/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param note
 * @param partOfSpeech
 * @param source
 * @param text
 */
data class SimpleDefinition(
        val note: String? = null,
        val partOfSpeech: String? = null,
        val source: String? = null,
        val text: String? = null
)

