/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param id
 * @param text
 * @param title
 * @param url
 */
data class SimpleExample(
        val id: Long? = null,
        val text: String? = null,
        val title: String? = null,
        val url: String? = null
)

