/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param displayName 
 * @param email 
 * @param faceBookId 
 * @param id 
 * @param password 
 * @param status 
 * @param userName 
 * @param username 
 */
data class User (
    val displayName: kotlin.String? = null,
    val email: kotlin.String? = null,
    val faceBookId: kotlin.String? = null,
    val id: kotlin.Long? = null,
    val password: kotlin.String? = null,
    val status: kotlin.Int? = null,
    val userName: kotlin.String? = null,
    val username: kotlin.String? = null
) {

}

