/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param createdAt
 * @param id
 * @param numberCommentsOnWord
 * @param numberLists
 * @param userId
 * @param username
 * @param word
 */
data class WordListWord(
        val id: Long,
        val createdAt: java.time.LocalDateTime? = null,
        val numberCommentsOnWord: Long? = null,
        val numberLists: Long? = null,
        val userId: Long? = null,
        val username: String? = null,
        val word: String? = null
)

