/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param category
 * @param contentProvider
 * @param createdAt
 * @param createdBy
 * @param definitions
 * @param examples
 * @param htmlExtra
 * @param id
 * @param note
 * @param parentId
 * @param publishDate
 * @param word
 */
data class WordOfTheDay(
        val id: Long,
        val category: String? = null,
        val contentProvider: ContentProvider? = null,
        val createdAt: java.time.LocalDateTime? = null,
        val createdBy: String? = null,
        val definitions: Array<String>? = null,
        val examples: Array<String>? = null,
        val htmlExtra: String? = null,
        val note: String? = null,
        val parentId: String? = null,
        val publishDate: java.time.LocalDateTime? = null,
        val word: String? = null
)

