/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param canonicalForm 
 * @param id 
 * @param originalWord 
 * @param suggestions 
 * @param vulgar 
 * @param word 
 */
data class WordObject (
    val id: kotlin.Long,
    val canonicalForm: kotlin.String? = null,
    val originalWord: kotlin.String? = null,
    val suggestions: kotlin.Array<kotlin.String>? = null,
    val vulgar: kotlin.String? = null,
    val word: kotlin.String? = null
) {

}

