/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.ContentProvider

/**
 * 
 * @param category 
 * @param contentProvider 
 * @param createdAt 
 * @param createdBy 
 * @param definitions 
 * @param examples 
 * @param htmlExtra 
 * @param id 
 * @param note 
 * @param parentId 
 * @param publishDate 
 * @param word 
 */
data class WordOfTheDay (
    val id: kotlin.Long,
    val category: kotlin.String? = null,
    val contentProvider: ContentProvider? = null,
    val createdAt: java.time.LocalDateTime? = null,
    val createdBy: kotlin.String? = null,
    val definitions: kotlin.Array<kotlin.String>? = null,
    val examples: kotlin.Array<kotlin.String>? = null,
    val htmlExtra: kotlin.String? = null,
    val note: kotlin.String? = null,
    val parentId: kotlin.String? = null,
    val publishDate: java.time.LocalDateTime? = null,
    val word: kotlin.String? = null
) {

}

