/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param count 
 * @param lexicality 
 * @param word 
 */
data class WordSearchResult (
    val count: kotlin.Long? = null,
    val lexicality: kotlin.Double? = null,
    val word: kotlin.String? = null
) {

}

