/**
* api.wordnik.com
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 4.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param createdAt 
 * @param id 
 * @param numberCommentsOnWord 
 * @param numberLists 
 * @param userId 
 * @param username 
 * @param word 
 */
data class WordListWord (
    val id: kotlin.Long,
    val createdAt: java.time.LocalDateTime? = null,
    val numberCommentsOnWord: kotlin.Long? = null,
    val numberLists: kotlin.Long? = null,
    val userId: kotlin.Long? = null,
    val username: kotlin.String? = null,
    val word: kotlin.String? = null
) {

}

