/**
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.infrastructure.*
import io.swagger.client.models.WordList

class WordListsApi(basePath: String = "https://api.wordnik.com/v4") : ApiClient(basePath) {

    /**
     * Creates a WordList.
     *
     * @param authToken The auth token of the logged-in user, obtained by calling /account.{format}/authenticate/{username} (described above)
     * @param body WordList to create (optional)
     * @return WordList
     */
    @Suppress("UNCHECKED_CAST")
    fun createWordList(authToken: String, body: WordList): WordList {
        val localVariableBody: Any? = body
        val localVariableQuery: MultiValueMap = mapOf()
        val localVariableHeaders: Map<String, String> = mapOf("authToken" to authToken)
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/wordLists.json",
                query = localVariableQuery,
                headers = localVariableHeaders
        )
        val response = request<WordList>(
                localVariableConfig,
                localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as WordList
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }

}
